#!/usr/bin/env bash

# Exit immediately if a command fails
set -e

# --- CONFIGURATION ---
BASE_URL="http://localhost:8080"
TOTAL_USERS=3          # Number of parallel user sessions to simulate
REQUESTS_PER_USER=5   # How many loops each user runs
RANDOM_DELAY_MAX=1     # Max sleep time (seconds) between requests to vary traffic spikes

echo "====== Starting Observability Load Generator ======"
echo "Target: $BASE_URL"
echo "Concurrency: $TOTAL_USERS users running $REQUESTS_PER_USER loops each"
echo "--------------------------------------------------"

# Function simulating a single user session
simulate_user() {
  local user_num=$1
  local email="user_${user_num}_$(date +%s)@example.com"
  local username="user_${user_num}"
  local password="Password123!"

  # 1. Register a new user
  # Keep registration quiet unless it fails to avoid cluttering stdout
  local reg_response
  reg_response=$(curl -s -X POST "$BASE_URL/api/v1/auth/register" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"$username\",\"email\":\"$email\",\"password\":\"$password\"}")

  # 2. Login to get the JWT token
  local login_response
  login_response=$(curl -s -X POST "$BASE_URL/api/v1/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$email\",\"password\":\"$password\"}")

  local token
  token=$(echo "$login_response" | jq -r '.token // empty')

  if [ -z "$token" ] || [ "$token" == "null" ]; then
    echo "[User $user_num] Auth failed. Skipping load loop."
    return
  fi

  # Helper header for authenticated requests
  local auth_header="Authorization: Bearer $token"

  # 3. Create a basic Checklist to populate data for subsequent tasks
  local checklist_response
  checklist_response=$(curl -s -X POST "$BASE_URL/api/v1/checklists" \
    -H "$auth_header" \
    -H "Content-Type: application/json" \
    -d "{\"title\":\"Load Test Checklist $user_num\",\"description\":\"Generated by stress script\"}")
  
  local checklist_id
  checklist_id=$(echo "$checklist_response" | jq -r '.id // empty')

  # --- STRESS LOOP ---
  for ((i=1; i<=REQUESTS_PER_USER; i++)); do
    # Introducing slight variation so everything doesn't hit at the exact microsecond
    sleep "$(awk -v max="$RANDOM_DELAY_MAX" 'BEGIN{srand(); print rand()*max}')"

    # Action A: Create a Task
    local task_response
    task_response=$(curl -s -X POST "$BASE_URL/api/v1/tasks" \
      -H "$auth_header" \
      -H "Content-Type: application/json" \
      -d "{\"title\":\"Task $i by User $user_num\",\"description\":\"Stress test target\",\"priority\":\"HIGH\",\"checklistId\":\"$checklist_id\"}")
    
    local task_id
    task_id=$(echo "$task_response" | jq -r '.id // empty')

    # Action B: Get User Profile ('/me') to create lightweight, high-volume GET traffic
    curl -s -o /dev/null -w "[User $user_num] Loop $i - GET /auth/me STATUS: %{http_code}\n" \
      -X GET "$BASE_URL/api/v1/auth/me" -H "$auth_header"

    # Action C: Query List of Tasks with filtering parameters (stresses query execution paths)
    curl -s -o /dev/null -w "[User $user_num] Loop $i - GET /tasks (filtered) STATUS: %{http_code}\n" \
      -X GET "$BASE_URL/api/v1/tasks?completed=false&checklistId=$checklist_id" -H "$auth_header"

    # Action D: If the task was successfully created, Patch it to Complete and then Reopen it
    if [ -not -z "$task_id" ] && [ "$task_id" != "null" ]; then
      curl -s -o /dev/null -w "[User $user_num] Loop $i - PATCH /tasks/$task_id/complete STATUS: %{http_code}\n" \
        -X PATCH "$BASE_URL/api/v1/tasks/$task_id/complete" -H "$auth_header"

      curl -s -o /dev/null -w "[User $user_num] Loop $i - PATCH /tasks/$task_id/reopen STATUS: %{http_code}\n" \
        -X PATCH "$BASE_URL/api/v1/tasks/$task_id/reopen" -H "$auth_header"
    fi
  done
  
  echo "[User $user_num] Finished all loops."
}

# --- SPAWN BACKGROUND PROCESSES ---
for ((u=1; u<=TOTAL_USERS; u++)); do
  simulate_user "$u" &
done

# Wait for all background user scripts to finish execution
wait

echo "--------------------------------------------------"
echo "====== Stress Test Complete ======"