spring:
  application:
    name: projeto-cybersec-taskmanager
  
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-super-secret-key-for-dev-environment-123}
