services:
  app:
    image: ghcr.io/mateusnavarro77/projeto-cybersec-taskmanager:latest
    container_name: secure-task-manager-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "8080"

  nginx:
    image: nginx:1.25.2
    container_name: secure-task-manager-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
