name: Checagem de Dependências - OWASP Dependency Check (SCA)

on:
  workflow_call:
    secrets:
      NVD_API_KEY:
        required: true

jobs:
  dependency-check:
    name: OWASP Dependency Check - SCA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - uses: ./.github/actions/setup-java-maven

      - name: Get date for cache key
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Restore OWASP Dependency Check Database
        id: dependency-check-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.dependency-check
          key: dependency-check-database-${{ runner.os }}-${{ steps.date.outputs.date }}
          restore-keys: |
            dependency-check-database-${{ runner.os }}-

      - name: Run OWASP Dependency Check
        run: |
          ./mvnw -B dependency-check:check \
            -Dnvd.api.key=${{ secrets.NVD_API_KEY }} \
            -DdataDirectory=$HOME/.dependency-check

      - name: Save OWASP Dependency Check Database
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.dependency-check
          key: dependency-check-database-${{ runner.os }}-${{ steps.date.outputs.date }}

      - name: Upload Dependency Check HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-html-report
          path: target/dependency-check-report.html
          if-no-files-found: warn
