name: Deploy Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  dependency-check:
    uses: ./.github/workflows/dependency-check.yaml
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  build-image:
    needs:
      - unit-tests
      - integration-tests
      - dependency-check

    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
