name: Pipeline de Deploy (Entrega Contínua)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  dependency-check:
    uses: ./.github/workflows/dependency-check.yaml
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  sonar-analysis:
    needs:
      - unit-tests
      - integration-tests
      - dependency-check
    uses: ./.github/workflows/sonar-analysis.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-image:
    needs:
      - unit-tests
      - integration-tests
      - dependency-check
      - sonar-analysis
    uses: ./.github/workflows/build-image.yaml

  ssh-deploy:
    needs:
      - build-image
    uses: ./.github/workflows/ssh-deploy.yaml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
