name: Testes de integração

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-java-maven

      - name: Run Integration Tests with Coverage
        run: |
          ./mvnw clean verify \
            -Dspring.profiles.active=integrationtest \
            -Ddependency-check.skip=true

      - name: Upload Integration Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-integration-coverage-report
          path: target/site/jacoco-it/
          if-no-files-found: warn
