name: Testes Unitários e Cobertura de Código

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-maven

      - name: Run Unit Tests with Coverage
        run: ./mvnw test -Dspring.profiles.active=unittest

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-unit-coverage-report
          path: target/site/jacoco/
          if-no-files-found: warn
